import type { ClerkProvider } from "@clerk/nextjs";
import type { ComponentProps } from "react";

import { verificationCardAppearance } from "./verification-card-appearance";

type ClerkProviderProps = ComponentProps<typeof ClerkProvider>;

export const clerkAppearance = {
  cssLayerName: "clerk",
  variables: {
    colorPrimary: "#262626",
    colorPrimaryForeground: "#ffffff",
    colorDanger: "#b42318",
    colorSuccess: "#166534",
    colorWarning: "#92400e",
    colorNeutral: "#262626",
    colorForeground: "#262626",
    colorMuted: "#fafafa",
    colorMutedForeground: "#787878",
    colorBackground: "#ffffff",
    colorInput: "#fcfcfc",
    colorInputForeground: "#262626",
    colorBorder: "#e6e6e6",
    colorRing: "#767676",
    colorShadow: "#000000",
    borderRadius: "0px",
    fontFamily: "var(--font-inter), Arial, sans-serif",
    fontFamilyButtons: "var(--font-inter), Arial, sans-serif",
    fontSize: "14px",
    spacing: "1rem",
  },
} satisfies NonNullable<ClerkProviderProps["appearance"]>;

export const clerkLocalization = {
  backButton: "Back",
  dividerText: "",
  formButtonPrimary: "Continue with email",
  socialButtonsBlockButton: "Continue with {{provider|titleize}}",
  formButtonPrimary__verify: "Sign In",
  formFieldInputPlaceholder__emailAddress: "Enter your email address",
  identityPreviewEditButton__emailAddress: "Back",
  identityPreviewEditButton__identifier: "Back",
  identityPreviewEditButton__phoneNumber: "Back",
  signIn: {
    start: { title: "Join Inspora", titleCombined: "Join Inspora", subtitle: "", subtitleCombined: "" },
    emailCode: { title: "Enter your code", subtitle: "We sent a 6-digit code to", formTitle: "", resendButton: "Send again" },
  },
  signUp: {
    start: { title: "Join Inspora", titleCombined: "Join Inspora", subtitle: "", subtitleCombined: "" },
    emailCode: { title: "Enter your code", subtitle: "We sent a 6-digit code to", formTitle: "", formSubtitle: "", resendButton: "Send again" },
  },
} satisfies NonNullable<ClerkProviderProps["localization"]>;

export const publicAuthAppearance = {
  theme: "simple",
  options: {
    logoPlacement: "inside",
    logoImageUrl: "/brand/inspora-auth-mark.svg",
    logoLinkUrl: "/",
    socialButtonsPlacement: "top",
    socialButtonsVariant: "blockButton",
  },
  elements: {
    rootBox: { boxSizing: "border-box", width: "100%", minWidth: 0, maxWidth: "429px" },
    cardBox: {
      boxSizing: "border-box",
      width: "100%",
      minWidth: 0,
      maxWidth: "429px",
      border: 0,
      borderRadius: 0,
      boxShadow: "0 4px 18px rgba(38, 38, 38, 0.06), 0 1px 3px rgba(38, 38, 38, 0.05)",
    },
    card: verificationCardAppearance.card,
    logoBox: { height: "50px", marginBottom: 0 },
    logoImage: { width: "56px", height: "50px", objectFit: "contain" },
    header: { gap: "16px", marginBottom: 0, padding: 0, textAlign: "center" },
    headerTitle: { color: "#444444", fontSize: "24px", fontWeight: 500, lineHeight: "normal", letterSpacing: "-0.48px", textAlign: "center" },
    headerSubtitle: { color: "#aaa8ad", fontSize: "16px", fontWeight: 500, lineHeight: 1.2, letterSpacing: "-0.5px", textAlign: "center" },
    main: verificationCardAppearance.main,
    form: { gap: "16px" },
    formFieldRow: { gap: "8px" },
    formFieldLabel: "sr-only",
    formFieldInput: {
      boxSizing: "border-box", minHeight: "44px", border: "1px solid #e6e6e6", borderRadius: 0, backgroundColor: "#fcfcfc", backgroundImage: "url('/icons/auth-email.svg')", backgroundPosition: "16px center", backgroundRepeat: "no-repeat", backgroundSize: "20px 20px", padding: "12px 16px 12px 44px", color: "#262626", fontSize: "14px", fontWeight: 500, lineHeight: 1.4, letterSpacing: "-0.5px", boxShadow: "none",
      "&::placeholder": { color: "#aaa8ad", opacity: 1 },
      "&:focus": { borderColor: "#767676", boxShadow: "none" },
    },
    formButtonPrimary: {
      boxSizing: "border-box", minHeight: "44px", border: 0, borderRadius: 0, background: "#262626", padding: "12px 16px", color: "#ffffff", fontSize: "14px", fontWeight: 500, lineHeight: "normal", textTransform: "none", boxShadow: "0 2px 0 #000000",
      "&:hover, &:focus, &:active": { background: "#262626" },
      "&:disabled": { background: "#787878", color: "#ffffff" },
      "& svg": { display: "none" },
    },
    socialButtonsRoot: { gap: "16px" },
    socialButtons: { display: "flex", flexDirection: "column", gap: "16px" },
    socialButtonsBlockButton: {
      boxSizing: "border-box", minHeight: "44px", border: "1px solid #e6e6e6", borderRadius: 0, background: "#ffffff", padding: "12px 16px", color: "#000000", boxShadow: "0 1px 0 #cfcfcf",
      "&:hover, &:focus, &:active": { borderColor: "#e6e6e6", background: "#ffffff" },
    },
    socialButtonsBlockButtonText: { color: "#000000", fontSize: "14px", fontWeight: 500, lineHeight: 1.4, letterSpacing: "-0.5px" },
    socialButtonsBlockButtonText__x: { fontSize: 0, "&::after": { content: "\"Continue with X\"", fontSize: "14px" } },
    socialButtonsProviderIcon: { width: "20px", height: "20px" },
    lastAuthenticationStrategyBadge: { display: "none" },
    dividerRow: { gap: 0, margin: 0 },
    dividerLine: { background: "#e6e6e6" },
    dividerText: { display: "none" },
    footer: { display: "none" },
    backRow: { marginBottom: "16px" },
    backLink: { minHeight: "41px", border: "1px solid #e6e6e6", borderRadius: "8px", background: "#ffffff", padding: "12px 18px", color: "#262626", fontSize: "14px", fontWeight: 400, letterSpacing: "0.2px", boxShadow: "0 1px 1px #e6e6e6" },
    identityPreview: { position: "static", border: 0, background: "transparent", padding: 0, color: "#aaa8ad", boxShadow: "none" },
    identityPreviewText: { color: "#aaa8ad", fontSize: "16px", fontWeight: 700, lineHeight: 1.2 },
    identityPreviewEditButton: verificationCardAppearance.identityPreviewEditButton,
    otpCodeField: { width: "100%", gap: "16px" },
    otpCodeFieldInputs: {
      display: "grid",
      width: "100%",
      gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
      gap: "8px",
    },
    // This container wraps the entire six-slot row, not an individual digit.
    otpCodeFieldInputContainer: { width: "100%", minWidth: 0 },
    otpCodeFieldInput: {
      boxSizing: "border-box",
      width: "100%",
      height: "auto",
      minWidth: 0,
      aspectRatio: "1 / 1",
      border: "1px solid transparent",
      borderRadius: "8px",
      background: "#f0f0f0",
      color: "#262626",
      fontSize: "18px",
      boxShadow: "none",
      "&:focus": { borderColor: "#767676", background: "#f0f0f0", boxShadow: "none" },
    },
    formResendCodeLink: verificationCardAppearance.formResendCodeLink,
    alert: { border: "1px solid #e6e6e6", borderRadius: 0, background: "#fafafa", padding: "12px 16px", boxShadow: "none" },
    alertText: { fontSize: "13px", lineHeight: 1.4 },
  },
} satisfies NonNullable<ClerkProviderProps["appearance"]>;
