export const verificationCardAppearance = {
  card: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    maxWidth: "429px",
    position: "relative",
    border: 0,
    borderRadius: 0,
    background: "#ffffff",
    padding: "80px 40px",
    margin: 0,
    boxShadow: "none",
  },
  main: { gap: "24px" },
  identityPreviewEditButton: {
    boxSizing: "border-box",
    width: "70px",
    minHeight: "41px",
    border: "1px solid #e6e6e6",
    borderRadius: "8px",
    background: "#ffffff",
    padding: "12px 18px",
    color: "#262626",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: "normal",
    letterSpacing: "0.2px",
    boxShadow: "0 1px 1px #e6e6e6",
    "& > *": { display: "none" },
    "&::after": { content: '"Back"' },
  },
  formResendCodeLink: {
    color: "#262626",
    fontSize: "14px",
    fontWeight: 500,
    textDecoration: "underline",
    textUnderlineOffset: "2px",
    "&::before": {
      content: '"Nothing arrived? \"',
      display: "inline-block",
      marginRight: "4px",
      color: "#787878",
      fontWeight: 500,
      textDecoration: "none",
    },
  },
} as const;
