const verificationSelector = "&:has(.cl-otpCodeField)";

export const verificationCardAppearance = {
  card: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    maxWidth: "429px",
    position: "relative",
    border: 0,
    borderRadius: 0,
    background: "#ffffff",
    padding: "80px 40px",
    boxShadow: "none",
    [verificationSelector]: {
      height: "auto",
      minHeight: "489px",
      backgroundImage: "url('/brand/inspora-auth-mark.svg')",
      backgroundPosition: "center 80px",
      backgroundRepeat: "no-repeat",
      backgroundSize: "56px 50px",
      paddingTop: "135px",
    },
    [`${verificationSelector} .cl-logoBox`]: { display: "none" },
  },
  main: {
    gap: "24px",
    [verificationSelector]: { gap: 0, position: "static" },
    [`${verificationSelector} .cl-form`]: {
      position: "static",
      gap: "16px",
    },
    [`${verificationSelector} .cl-formButtonPrimary`]: {
      position: "absolute",
      top: "338px",
      right: "40px",
      boxSizing: "border-box",
      width: "87px",
      minHeight: "41px",
      borderRadius: "8px",
      color: "transparent",
      fontSize: 0,
    },
    [`${verificationSelector} .cl-formButtonPrimary > *`]: {
      display: "none",
    },
    [`${verificationSelector} .cl-formButtonPrimary::after`]: {
      content: '"Sign In"',
      color: "#ffffff",
      fontSize: "14px",
    },
    [`${verificationSelector} .cl-formResendCodeLink`]: {
      position: "absolute",
      top: "397px",
      left: "50%",
      width: "max-content",
      transform: "translateX(-50%)",
    },
  },
  identityPreviewEditButton: {
    position: "absolute",
    top: "338px",
    left: "40px",
    zIndex: 1,
    boxSizing: "border-box",
    width: "70px",
    minHeight: "41px",
    border: "1px solid #e6e6e6",
    borderRadius: "8px",
    background: "#ffffff",
    padding: "12px 18px",
    color: "#262626",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: "normal",
    letterSpacing: "0.2px",
    boxShadow: "0 1px 1px #e6e6e6",
    "& > *": { display: "none" },
    "&::after": { content: '"Back"' },
  },
  formResendCodeLink: {
    color: "#262626",
    fontSize: "14px",
    fontWeight: 500,
    textDecoration: "underline",
    textUnderlineOffset: "2px",
    "&::before": {
      content: '"Nothing arrived? "',
      display: "inline-block",
      color: "#787878",
      fontWeight: 500,
      textDecoration: "none",
    },
  },
} as const;
