const verificationSelector = "&:has(.cl-otpCodeField)";

export const verificationAppearanceElements = {
  card: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    maxWidth: "429px",
    position: "relative",
    border: 0,
    borderRadius: 0,
    background: "#ffffff",
    padding: "80px 40px",
    boxShadow: "none",
    [verificationSelector]: {
      backgroundImage: "url('/brand/inspora-auth-mark.svg')",
      backgroundPosition: "center 80px",
      backgroundRepeat: "no-repeat",
      backgroundSize: "56px 50px",
      paddingTop: "150px",
    },
    [`${verificationSelector} .cl-logoBox`]: { display: "none" },
  },
  main: {
    gap: "24px",
    [verificationSelector]: {
      display: "grid",
      gridTemplateColumns: "70px 87px",
      justifyContent: "space-between",
      columnGap: "16px",
      rowGap: "16px",
    },
    [`${verificationSelector} .cl-identityPreview`]: { display: "contents" },
    [`${verificationSelector} .cl-identityPreviewText`]: {
      gridColumn: "1 / -1",
      gridRow: "1",
      justifySelf: "center",
      textAlign: "center",
    },
    [`${verificationSelector} .cl-identityPreviewEditButton`]: {
      gridColumn: "1",
      gridRow: "3",
      boxSizing: "border-box",
      width: "70px",
      minHeight: "41px",
      alignSelf: "start",
      border: "1px solid #e6e6e6",
      borderRadius: "8px",
      background: "#ffffff",
      padding: "12px 18px",
      color: "#262626",
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "normal",
      letterSpacing: "0.2px",
      boxShadow: "0 1px 1px #e6e6e6",
    },
    [`${verificationSelector} .cl-identityPreviewEditButton > *`]: {
      display: "none",
    },
    [`${verificationSelector} .cl-identityPreviewEditButton::after`]: {
      content: '"Back"',
    },
    [`${verificationSelector} .cl-form`]: { display: "contents" },
    [`${verificationSelector} .cl-formFieldRow`]: {
      gridColumn: "1 / -1",
      gridRow: "2",
    },
    [`${verificationSelector} .cl-otpCodeField`]: {
      gridColumn: "1 / -1",
      gridRow: "2",
    },
    [`${verificationSelector} .cl-formButtonPrimary`]: {
      gridColumn: "2",
      gridRow: "3",
      boxSizing: "border-box",
      width: "87px",
      minHeight: "41px",
      justifySelf: "end",
      alignSelf: "start",
      borderRadius: "8px",
      fontSize: 0,
    },
    [`${verificationSelector} .cl-formButtonPrimary::after`]: {
      content: '"Sign In"',
      fontSize: "14px",
    },
    [`${verificationSelector} .cl-formResendCodeLink`]: {
      gridColumn: "1 / -1",
      gridRow: "4",
      justifySelf: "center",
    },
  },
  formResendCodeLink: {
    color: "#262626",
    fontSize: "14px",
    fontWeight: 500,
    textDecoration: "underline",
    textUnderlineOffset: "2px",
    "&::before": {
      content: '"Nothing arrived? "',
      display: "inline-block",
      color: "#787878",
      fontWeight: 500,
      textDecoration: "none",
    },
  },
} as const;
